---

name: Build address book
on:
#   schedule:
#     - cron: '0 6,14 * * 1-6'
  workflow_dispatch:
  push:
jobs:
  build-address-book:
    runs-on: ubuntu-22.04
    env:
      # Provider chain variables
      CHAIN_BINARY: gaiad
      CHAIN_BINARY_URL: https://github.com/cosmos/gaia/releases/download/v14.1.0/gaiad-v14.1.0-linux-amd64
      CHAIN_ID: provider
      RPC_NODE: https://rpc.provider-sentry-02.rs-testnet.polypore.xyz:443
      API_NODE: https://rest.provider-sentry-02.rs-testnet.polypore.xyz:443
    steps:
      - name: Update PATH
        run: |
          mkdir -p $HOME/go/bin
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Bypass the grub-efi-amd64-signed package
        run: sudo apt-mark hold grub-efi-amd64-signed
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install toml-cli requests command
      - name: Download chain binary
        run: |
          wget $CHAIN_BINARY_URL -O $HOME/go/bin/$CHAIN_BINARY
          chmod +x $HOME/go/bin/$CHAIN_BINARY
      - name: Check chain version
        run: $CHAIN_BINARY version --long
      - name: Generate RS testnet address book
        run: |
          python -m address_book.address_book -r $RPC_NODE -a $API_NODE -o provider-address-book.csv
      - name: Check address book
        run: |
          ls -la
          cat provider-address-book.csv
      - name: Commit to repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add provider-address-book.csv
          git commit -m "Updated address book"
