---

name: Build address books
on:
#   schedule:
#     - cron: '0 6,14 * * 1-6'
  workflow_dispatch:
  push:
jobs:
  build-address-book:
    runs-on: ubuntu-22.04
    env:
      # Provider chain variables
      CHAIN_BINARY: gaiad
      CHAIN_BINARY_URL: https://github.com/cosmos/gaia/releases/download/v14.1.0/gaiad-v14.1.0-linux-amd64
      CHAIN_ID: provider
      PROVIDER_RPC_NODE: https://rpc.provider-sentry-02.rs-testnet.polypore.xyz:443
      PROVIDER_API_NODE: https://rest.provider-sentry-02.rs-testnet.polypore.xyz:443
      HUB_RPC_NODE: https://rpc.one.cosmos-mainnet.polypore.xyz:443
      HUB_API_NODE: https://cosmoshub-api.cosmosrescue.dev:443
    steps:
      - name: Update PATH
        run: |
          mkdir -p $HOME/go/bin
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Bypass the grub-efi-amd64-signed package
        run: sudo apt-mark hold grub-efi-amd64-signed
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install toml-cli requests command
      - name: Download chain binary
        run: |
          wget $CHAIN_BINARY_URL -O $HOME/go/bin/$CHAIN_BINARY
          chmod +x $HOME/go/bin/$CHAIN_BINARY
      - name: Check chain version
        run: $CHAIN_BINARY version --long
      - name: Remove existing address books
        run: |
          touch output/address-book
          rm output/*address-book*
      - name: Generate RS testnet address book
        run: |
          python -m address_book.address_book -r $PROVIDER_RPC_NODE -a $PROVIDER_API_NODE -c provider
      - name: Generate Hub address book
        run: |
          python -m address_book.address_book -r $HUB_RPC_NODE -a $HUB_API_NODE -c cosmoshub-4
      - name: Commit to repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Updated address book"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}